### PR TITLE
fix typo in feedstock's metadata

### PR DESCRIPTION
**Pull request by andersy005**

### CODE REVIEW

**Comment by andersy005** [comment]
@cisaacstern, it turns out we don't have `pangeo-notebook-version` defined in the feedstock's metadata

https://github.com/pangeo-forge/casm-feedstock/blob/41d84f145146c240d64ca07956991d45dc346bde/feedstock/meta.yaml#L3

is this field optional or should we define it?

**Comment by cisaacstern** [comment]
@andersy005, both `pangeo_forge_version` and `pangeo_notebook_version` are currently ignored.

Once https://github.com/pangeo-forge/pangeo-forge-runner/issues/27 is resolved, we will be dynamically generating envs for each recipe, but until then, these fields are not used.

**Comment by andersy005** [comment]
thank you for the clarification, @cisaacstern! by the way, could you merge this when you get a chance? I currently don't have the necessary permissions to do so myself.

**Comment by cisaacstern** [comment]
@andersy005 just promoted your role in the `pangeo-forge` org... can you try merge now?

**Comment by andersy005** [comment]
Thank you, @cisaacstern!

**Pull request merged**
